### PR TITLE
Check args default values and consistency

### PR DESCRIPTION
**Pull request by Bisaloo**
* **Please check if the PR fulfills these requirements**

- [ ] I have read the CONTRIBUTING guidelines 
- [ ] A new item has been added to `NEWS.md`
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

~~This branch should be rebased on `main` once `develop` has been merged and we switch to working directly with PR to `main`.~~

### CODE REVIEW

**Comment by Karim-Mane** [comment]
@Bisaloo kindly review this when you have time. thanks

**Review by Bisaloo — COMMENTED** [review]
Thanks for the changes. Two comments:

- I see some unrelated changes in this PR:
  - modification of `README.md`. You don't need to touch this file since it's automatically re-render by our GitHub Actions workflow. Could you remove the last commit from this PR please? It can be done by running `git rebase -i main` and deleting this commit line.
  - deletion of `CITATION.cff`. I can restore it since this is slightly more complex git operation

- argument defaults: to be sure we are on the same page. I am not saying all arguments should have defaults. Just that if an argument has a default for DHIS2, it should have one for fingertips or readcap as well. I trust your knowledge of the package to decide which arguments should have defaults or not. It can also be useful to request assistance from a potential test user here (@Degoot-AM?). Please go through all functions again and see what defaults need to be kept.

**Comment by Karim-Mane** [comment]
@Bisaloo kindly review this PR when you have time. Note that there are commits that I made to fix conflicts with main

**Comment by Bisaloo** [comment]
Work will continue in #62 because this branch history was mixed with main and I don't want to force push in case any important change was added during conflict resolution.

**Pull request closed without merging**
