### PR TITLE
PR to add modifications generated during the CRAN submission process into main

### PR DESCRIPTION
**Pull request by Karim-Mane**

### CODE REVIEW

**Review by Bisaloo — CHANGES_REQUESTED** [review]
Can you point out the specific commits that were added during the process so we can cherry-pick them and not carry the entire branch history?

**Comment by Karim-Mane** [comment]
Except from coomit `8b0bc94`, all commits on this PR are related to the modifications I made when I was going through the CRAN submission process and pulling your updates from main.

`8b0bc94` is where I added the changes related to function's argument order and default values and argument order consistency across functions.

**Comment by Bisaloo** [comment]
> Except from coomit 8b0bc94, all commits on this PR are related to the modifications I made when I was going through the CRAN submission process and pulling your updates from main.

I don't follow. This PR includes commits from 9 months that seem completely unrelated to the CRAN submission. My understanding is that the CRAN changes start at [`b952088` (#57)](https://github.com/epiverse-trace/readepi/pull/57/commits/b952088b41a617236175692f598b894cfd7d57f7) and end at [`f917a8d` (#57)](https://github.com/epiverse-trace/readepi/pull/57/commits/f917a8d3f90f82135e3ac054364126ceedfd62de).

Am I missing something or do you confirm this assessment?

**Comment by Karim-Mane** [comment]
The commit history contains the list of all commits I have made since several months ago.

The commits that are related to the CRAN submission process and the merging of the most recent updates you made on main are those between `e4c5222` and `0c4276b`.

The commit that contains changes I made to fix arguments order and function default values is `8b0bc94`.

**Comment by Bisaloo** [comment]
> The commit history contains the list of all commits I have made since several months ago.

Thanks, we're on a agreement then. Could you clean this branch history to keep only the relevant new commits please? This is necessary to get a clear view of what has changed and what needs to be reviewed. Let's jump on a zoom call if you're unsure how to do this.

**Review by Bisaloo — APPROVED** [review]
Thanks, looks good to me. Two changes are necessary before merging:

- delete `doc/`
- delete `revdep/`

**Comment by Karim-Mane** [comment]
Ideally No - given that I have the modifications that account for args default values and order in it.

I have cherry-picked it into `arg-defaults` instead.

**Comment by Karim-Mane** [comment]
@Bisaloo can you please review this when you are free. Thanks

**Pull request merged**
